### ISSUE TITLE
SwiftAsyncReadPacket.swift:251:29: Generic parameter 'Element' could not be inferred

### ISSUE THREAD

**Issue by mauker** [chouheiwa/SwiftAsnycSocket#2]
I try to run using the last Xcode and for swift 13 and get this error, could you help me?

![Screen Shot 2021-01-24 at 20 55 12](https://user-images.githubusercontent.com/476273/105647775-a3b35680-5e86-11eb-966b-17cb46f470a5.png)

**Comment by wuxiaohua1011** [comment]
Same issue here!

**Comment by Guru7373** [comment]
Found any solution ?

**Comment by Guru7373** [comment]
<img width="537" alt="Screenshot 2022-05-12 at 11 16 45 AM" src="https://user-images.githubusercontent.com/38368984/168000527-322737c5-ec4f-4f60-ab2d-af90f9446aa6.png">

Is this valid ?

**Comment by chouheiwa** [comment]
Hey guys, I have fixed this error in 0.2.0.
And you can upgrade to the latest version.

**Comment by Guru7373** [comment]
> 

Is 0.2.0 available on the master branch ?

**Comment by Guru7373** [comment]
Thanks
